### ISSUE TITLE
Infinite loop - docker-compose up

### ISSUE THREAD

**Issue by MKatereggaExigent** [docfex/docfex#20]
Hi there,

First, this is a very great project.

I tried to clone and run it on a Debian 10 server by just calling: `sudo docker-compose up`. However I get into an infinite loop with error `ModuleNotFoundError: No module named 'src.config.config'`

I did include the `config.py` file in `src` but still it doesn't work.

Any advise is greatly appreciated.

**Comment by mhatzl** [comment]
Hello,

thanks for trying out my project.
You need to put config.py under src/config/ which is the same location as the config.py.example.

I hope this resolves your problem.

**Comment by MKatereggaExigent** [comment]
Yes it does, thank you @mhatzl but now its taking forever to connect to elastic:

`WARNING:root:Can't connect to elastic, retrying in 10 seconds`

**Comment by mhatzl** [comment]
How many items (pdf, markdown, ...) have you setup?
Depending on the number, it can take several minutes/hours for the first time to get everything read and indexed by elastic.

If it takes too long, try only like 10 documents first. My highest was around 1000 and it took over 5 hours to run.

**Comment by MKatereggaExigent** [comment]
Oh I guess that is where my problem is - I had thought I would get the engine running first then upload the files from the front end. So I basically have to set add a directory say `data` and add my items - pdf, markdown and configure that path in `config.py`?

**Comment by mhatzl** [comment]
Yes. From the frontend side you can't "upload" any data. 
My idea was that you have a folder on your system with pdf, markdown, ... files and you want to search inside those files.

Hope this helps you

**Comment by MKatereggaExigent** [comment]
This is perfect @mhatzl Thank you very much - your idea is brilliant. I would love to add a machine learning model like Spacy or NLP for text labelling/annotation. We can close this ticket.
