### ISSUE TITLE
Changing default ip 

### ISSUE THREAD

**Issue by MKatereggaExigent** [docfex/docfex#21]
Hi @mhatzl  so I managed to config the application to run on my server but now I want to change the default ip from `localhost` or `127.0.0.1` to my own `xxx.xxx.xxx.xxx`. Do you know how I can achieve that.

I tried `xxx.xxx.xxx.xxx:5009:5000` but it didn't work.

**Comment by mhatzl** [comment]
Hi. You are using docker-compose, right? Can you curl your website locally where docker is running? Changing the ip inside config.py won't work with docker, as far as I know.
If you can curl your website locally by localhost or 127.0.0.1, the best would be to use apache, nginx or similar and use them as reverse proxies to your site.

**Comment by MKatereggaExigent** [comment]
@mhatzl  yes I am using docker-compose and not on my local machine. I decided to run the application on a `Debian 10 server` with address `xxx.xxx.xxx.xxx`. my local `OS` is `Windows` and was giving me lots of issues that is why I decided on the server. Can't I pass `xxx.xxx.xxx.xxx:5009` as a flag to `docker-compose`?

**Comment by mhatzl** [comment]
You should be able to do that in the docker-compose file. But before that, can you curl the website locally on your server?
But still I would suggest using nginx or apache as a reverse proxy to your docker website

**Comment by MKatereggaExigent** [comment]
Alright, I will try that. Thanks @mhatzl

**Comment by MKatereggaExigent** [comment]
@mhatzl  So I manged to get the app to run by:

`python -m flask run --host xxx.xxx.xxx.xxx --port 5000`

However, I get

**Not Found**
`The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again`

When I turned the `debug` on the error was `no module src.main`

**Comment by mhatzl** [comment]
Are you running it from the src folder?
You should run `python main.py` to get the python-side up and running.
By just running the flask-part dependencies break, because it wants access to other functionalities.

The problem is that my university started last week so I don't have that much time at the moment and it has been around 1 year that I last used it.

Since I am not that happy with the current performance I thought about rewritting most parts of the code, but that will unfortunately have to wait till summer 2021 I guess.

I still hope I can help you with minor issues and thanks for trying it out!

**Comment by MKatereggaExigent** [comment]
@mhatzl  this is absolutely fine. You don't usually get this much help from developers because of time so I indeed appreciate your time and effort to help.

I am running it from `root` where the `main.py` resides. So you saying instead of the usual `python -m flask run` I should instead do `python main.py`? Ok I will try that.

**Comment by mhatzl** [comment]
@MKatereggaExigent yes exactly. Running `python main.py` will start docfex. However, you will need to have your own Elasticsearch-Instance running that docfex can connect to.
This is described in [InstallFromSource.md](https://github.com/docfex/docfex/blob/master/doc/Installation/InstallFromSource.md)

**Comment by MKatereggaExigent** [comment]
@mhatzl  yes I figured that was the issue why the app was not working normally. I guess I can obtain a free license of elasticsearch to test.

**Comment by mhatzl** [comment]
@MKatereggaExigent Elasticsearch shoul be free. Checkout [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html)

**Comment by MKatereggaExigent** [comment]
@mhatzl  Thanks - I will have a look, see if I can it installed, configured and running. Thank you once again @mhatzl  I will close this ticket now.
